{% set name = "yazi" %}
{% set version = "25.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sxyazi/yazi/archive/v{{ version }}.tar.gz
  sha256: d3879b85465e036abfd69c53488e9bc90c9ad52a31080511a0fcd1b11f81f10b

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - make  # [linux]
    - cargo-bundle-licenses

test:
  commands:
    - yazi --help

about:
  home: https://github.com/sxyazi/yazi
  summary: 'Blazing fast terminal file manager written in Rust, based on async I/O'
  description: |
    Yazi (means "duck") is a terminal file manager written in Rust,
    based on non-blocking async I/O. It aims to provide an efficient,
    user-friendly, and customizable file management experience.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-ICONS
    - THIRDPARTY.yml
  doc_url: https://yazi-rs.github.io/
  dev_url: https://github.com/sxyazi/yazi

extra:
  recipe-maintainers:
    - hoxbro
